# Generated by Django 6.1 on 2026-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_livro_n_paginas_alter_livro_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
