# Generated by Django 6.1 on 2026-08-28 15:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='n_paginas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O número de páginas deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='O valor não pode ser negativo.')]),
        ),
    ]
